### ISSUE TITLE
Refactor streams support

### ISSUE THREAD

**Issue by difabion** [difabion/benthos-helm-chart#8]
Currently an operator must list all streams config files in `values.yaml` like this:

```yaml
streams: enabled
  streamsConfigMap: benthos-streams
  streamsConfigFilenames:
    - hello.yaml
    - aaaaa.yaml
```

Benthos has support for globs in filenames specified after the streams subcommand committed, so the next tagged build should include the changes.  Refactor the chart afterwards so that the filenames will be pulled in automatically.
